# Turn on lights with a resettable off timer
# This recipe will turn on a light when there is motion and turn off 
# the light when ten minutes has passed without any motion events .

automation:
  alias: Turn on kitchen lights when there is movement 
  trigger:
    - platform: state
      entity_id: sensor.motion_sensor
      to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_lamp

script:
  timed_lamp:
    alias: "Turn on lamp and set timer"
    sequence:
      # Cancel ev. old timers 
      - execute_service: script.turn_off
        service_data: 
           entity_id: script.timer_off
      - execute_service: light.turn_on
        service_data:
          entity_id: light.kitchen
      # Set new timer 
      - execute_service: script.turn_on
        service_data:
          entity_id: script.timer_off

  timer_off:
    alias: "Turn off lamp after 10 minutes"
    sequence:
      - delay:
          minutes: 10
      - execute_service: light.turn_off
        service_data: 
          entity_id: light.kitchen

################################################################################

# Basic example for use_trigger_values
# Turn on lights during daytime when it's dark enough < 200 lux.

automation:
  - alias: 
    trigger:
      - platform: numeric_state
        entity_id: sensor.sensor_luminance
        below: 200
      - platform: time
        after: "08:00"
        before: "23:00"
    condition: use_trigger_values
    action:
      service: homeassistant.turn_on
      entity_id: group.basic_lights

automation 2:
  - alias: 
    trigger:
      - platform: numeric_state
        entity_id: sensor.sensor_luminance
        above: 200
      - platform: time
        after: "23:00"
    action:
      service: homeassistant.turn_off
      entity_id: group.basic_lights

# Entry way light when you get home
# Uses the presence awareness to turn on a house light if it's nighttime
# but only during reasonable hours'. (to guard against iPhones dropping
# on/off wifi in the middle of the night)

  alias: 'Kitchen Light Helper'

  trigger:
   - platform: state
     entity_id: group.all_devices
     state: 'home'

  condition:
   - platform: state
     entity_id: group.all_devices
     state: 'home'
   - platform: state
     entity_id: sun.sun
     state: 'below_horizon'
   - platform: time
     after: '16:00'
     before: '00:00'

  action:
     service: light.turn_on
     entity_id: light.fan_bulb_1