######################################################
###                                                ###
###                       Covers                   ###
###                                                ###
######################################################

- platform: mqtt
  name: "Living room blinds1"
  command_topic: "livingroom/switch/blind1"
  state_topic: "livingroom/switch/blind1"
  availability_topic: "livingroom/switch/blind1"
  qos: 0
  retain: true
  payload_open: "ON"
  payload_close: "OFF"
  payload_stop: "STOP"
  state_open: "ON"
  state_closed: "OFF"
  payload_available: "online"
  payload_not_available: "offline"
  optimistic: false
  value_template: '{{ value.x }}'
  tilt_command_topic: 'livingroom/switch/blind1'
  tilt_status_topic: 'livingroom/switch/blind1'
  tilt_min: 0
  tilt_max: 180
  tilt_closed_value: 0
  tilt_opened_value: 180